// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ethvslvspbadlczyojdc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0aHZzbHZzcGJhZGxjenlvamRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU0NDkwNjIsImV4cCI6MjA5MTAyNTA2Mn0.xVXZ74Esekg2QryqyG65NQ3Q3FBQF3ssX2qOgJi22v0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});